# Basic parameters of the build
sudo: required
dist: trusty
group: edge
language: cpp
compiler: gcc

# Blacklist - make sure we don't try to build gh-pages branch
branches:
  except:
    - gh-pages

# Environment variables
env:
  global:
    - GH_REPO_NAME: possumwood
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - GH_REPO_REF: github.com/martin-pr/possumwood.git
    - COMPILER: g++-5

# Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-all-dev
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - gcc-5
      - g++-5
      - freeglut3-dev
      - qtbase5-dev
      - qt5-default
      - libqt5opengl5-dev
      - libxmu-dev
      - libxi-dev
      - cmake
      - libglew-dev
      - libmpfr-dev

before_install:
  - sudo apt-get update -qq

# Run build
script:
  - wget http://www.mprazak.info/cgal-releases-CGAL-4.11.tar.gz
  - tar -xzvf cgal-releases-CGAL-4.11.tar.gz
  - pushd cgal-releases-CGAL-4.11 && mkdir build && pushd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr && make && sudo make install && popd && popd

  - export CXX=g++-5
  - export CC=gcc-5
  - cd $TRAVIS_BUILD_DIR
  - ./tools/build-debug -j 4
  - ./tools/run-tests

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - ./tools/build-docs
